// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi7cemT4KWTa9zohFqPGq9cqRqt7O1cd0',
    appId: '1:1008718709445:web:ed96194c9678c8aae426ac',
    messagingSenderId: '1008718709445',
    projectId: 'instagram-1248',
    authDomain: 'instagram-1248.firebaseapp.com',
    storageBucket: 'instagram-1248.appspot.com',
    measurementId: 'G-XGVSM7N9C4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4Sje6Ht7IDajpjxd9Kcq9qVLL6Yq1Htg',
    appId: '1:1008718709445:android:63b3005d708dceabe426ac',
    messagingSenderId: '1008718709445',
    projectId: 'instagram-1248',
    storageBucket: 'instagram-1248.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeLv2glmAFN6_2H2qa17ImvSdRIVth7XQ',
    appId: '1:1008718709445:ios:26468f59cdd47b90e426ac',
    messagingSenderId: '1008718709445',
    projectId: 'instagram-1248',
    storageBucket: 'instagram-1248.appspot.com',
    iosClientId: '1008718709445-jujip0ih4575kcr2gldpgltup8skm4m2.apps.googleusercontent.com',
    iosBundleId: 'com.example.testTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeLv2glmAFN6_2H2qa17ImvSdRIVth7XQ',
    appId: '1:1008718709445:ios:26468f59cdd47b90e426ac',
    messagingSenderId: '1008718709445',
    projectId: 'instagram-1248',
    storageBucket: 'instagram-1248.appspot.com',
    iosClientId: '1008718709445-jujip0ih4575kcr2gldpgltup8skm4m2.apps.googleusercontent.com',
    iosBundleId: 'com.example.testTest',
  );
}
